/* ============================================================
   PANTRY + RECIPE DATA
   Sean: this is the only file you normally need to hand-edit.
   - INGREDIENTS: the master checklist shown on the page.
       staple:true  -> checked by default (things you're never out of)
   - RECIPES: everything makeable, tagged with ingredient ids.
       mixer:true   -> only offered when "mixer/grinder" is on
   ============================================================ */

const INGREDIENTS = [
  // ---------- VEGETABLES ----------
  { id:'onion',       cat:'veg', en:'Onion',            mr:'कांदा',            hi:'प्याज',            tr:'kanda' },
  { id:'tomato',      cat:'veg', en:'Tomato',           mr:'टोमॅटो',           hi:'टमाटर',           tr:'tomato' },
  { id:'potato',      cat:'veg', en:'Potato',           mr:'बटाटा',            hi:'आलू',             tr:'batata' },
  { id:'carrot',      cat:'veg', en:'Carrot',           mr:'गाजर',             hi:'गाजर',            tr:'gajar' },
  { id:'cauliflower', cat:'veg', en:'Cauliflower',      mr:'फ्लॉवर',            hi:'फूलगोभी',          tr:'flower' },
  { id:'cabbage',     cat:'veg', en:'Cabbage',          mr:'कोबी',             hi:'पत्ता गोभी',        tr:'kobi' },
  { id:'broccoli',    cat:'veg', en:'Broccoli',         mr:'ब्रोकोली',          hi:'ब्रोकली',          tr:'broccoli' },
  { id:'beans',       cat:'veg', en:'Green beans',      mr:'बीन्स',             hi:'बीन्स',            tr:'beans' },
  { id:'peas',        cat:'veg', en:'Peas',             mr:'मटार',             hi:'मटर',             tr:'matar' },
  { id:'pumpkin',     cat:'veg', en:'Pumpkin',          mr:'भोपळा',            hi:'कद्दू',            tr:'bhopla' },
  { id:'bhindi',      cat:'veg', en:'Okra / bhindi',    mr:'भेंडी',             hi:'भिंडी',            tr:'bhendi' },
  { id:'sweetpotato', cat:'veg', en:'Sweet potato',     mr:'रताळे',            hi:'शकरकंद',          tr:'ratale' },
  { id:'dudhi',       cat:'veg', en:'Bottle gourd',     mr:'दुधी भोपळा',        hi:'लौकी',            tr:'dudhi' },
  { id:'cucumber',    cat:'veg', en:'Cucumber',         mr:'काकडी',            hi:'खीरा',            tr:'kakdi' },
  { id:'drumstick',   cat:'veg', en:'Drumstick',        mr:'शेवगा',            hi:'सहजन',            tr:'shevga' },
  { id:'capsicum',    cat:'veg', en:'Capsicum',         mr:'ढोबळी मिरची',       hi:'शिमला मिर्च',      tr:'dhobli mirchi' },
  { id:'beetroot',    cat:'veg', en:'Beetroot',         mr:'बीट',              hi:'चुकंदर',           tr:'beet' },

  // ---------- GREENS & HERBS ----------
  { id:'spinach',     cat:'greens', en:'Spinach',       mr:'पालक',             hi:'पालक',            tr:'palak' },
  { id:'coriander',   cat:'greens', en:'Coriander leaves', mr:'कोथिंबीर',       hi:'धनिया',           tr:'kothimbir' },
  { id:'curryleaf',   cat:'greens', en:'Curry leaves',  mr:'कढीपत्ता',          hi:'करी पत्ता',        tr:'kadhipatta' },
  { id:'mint',        cat:'greens', en:'Mint',          mr:'पुदिना',            hi:'पुदीना',           tr:'pudina' },
  { id:'methi',       cat:'greens', en:'Methi leaves',  mr:'मेथी',              hi:'मेथी',             tr:'methi' },
  { id:'shepu',       cat:'greens', en:'Dill / shepu',  mr:'शेपू',              hi:'सोआ',             tr:'shepu' },
  { id:'moringa',     cat:'greens', en:'Moringa powder', mr:'शेवग्याच्या पानांची पूड', hi:'मोरिंगा पाउडर', tr:'moringa powder' },

  // ---------- DALS, GRAINS & FLOURS ----------
  { id:'moongdal',    cat:'grain', en:'Yellow moong dal', mr:'पिवळी मूग डाळ',   hi:'पीली मूंग दाल',    tr:'moong dal', staple:true },
  { id:'toordal',     cat:'grain', en:'Toor dal',       mr:'तूर डाळ',           hi:'तूर दाल',          tr:'toor dal', staple:true },
  { id:'chanadal',    cat:'grain', en:'Chana dal',      mr:'चणा डाळ',           hi:'चना दाल',          tr:'chana dal' },
  { id:'masoordal',   cat:'grain', en:'Masoor dal',     mr:'मसूर डाळ',          hi:'मसूर दाल',         tr:'masoor dal' },
  { id:'uraddal',     cat:'grain', en:'Urad dal',       mr:'उडीद डाळ',          hi:'उड़द दाल',         tr:'urad dal' },
  { id:'chickpeas',   cat:'grain', en:'Chickpeas',      mr:'काबुली चणे',         hi:'काबुली चना',       tr:'kabuli chana' },
  { id:'rice',        cat:'grain', en:'Rice',           mr:'तांदूळ',            hi:'चावल',            tr:'tandul', staple:true },
  { id:'basmati',     cat:'grain', en:'Basmati rice',   mr:'बासमती तांदूळ',      hi:'बासमती चावल',      tr:'basmati' },
  { id:'poha',        cat:'grain', en:'Poha',           mr:'पोहे',              hi:'पोहा',             tr:'pohe' },
  { id:'rava',        cat:'grain', en:'Rava / semolina', mr:'रवा',              hi:'सूजी',             tr:'rava' },
  { id:'besan',       cat:'grain', en:'Besan',          mr:'बेसन',              hi:'बेसन',             tr:'besan' },
  { id:'atta',        cat:'grain', en:'Wheat flour',    mr:'कणिक',              hi:'आटा',             tr:'kanik', staple:true },
  { id:'jowar',       cat:'grain', en:'Jowar / bajra flour', mr:'ज्वारीचे पीठ',   hi:'ज्वार का आटा',     tr:'jwariche pith' },
  { id:'idlibatter',  cat:'grain', en:'Idli batter (store-bought)', mr:'इडली पीठ', hi:'इडली बैटर',    tr:'idli batter' },
  { id:'roastedgram', cat:'grain', en:'Roasted gram (dalia)', mr:'डाळं',        hi:'भुना चना',         tr:'dalya' },

  // ---------- SPICES & STAPLES ----------
  { id:'salt',        cat:'spice', en:'Salt',           mr:'मीठ',              hi:'नमक',             tr:'meeth', staple:true },
  { id:'oil',         cat:'spice', en:'Oil',            mr:'तेल',              hi:'तेल',              tr:'tel', staple:true },
  { id:'turmeric',    cat:'spice', en:'Turmeric',       mr:'हळद',              hi:'हल्दी',            tr:'halad', staple:true },
  { id:'jeera',       cat:'spice', en:'Cumin seeds',    mr:'जिरे',              hi:'जीरा',             tr:'jire', staple:true },
  { id:'mustard',     cat:'spice', en:'Mustard seeds',  mr:'मोहरी',             hi:'सरसों',            tr:'mohri', staple:true },
  { id:'hing',        cat:'spice', en:'Hing / asafoetida', mr:'हिंग',           hi:'हींग',             tr:'hing', staple:true },
  { id:'dhaniapdr',   cat:'spice', en:'Coriander powder', mr:'धणे पूड',         hi:'धनिया पाउडर',      tr:'dhane pud', staple:true },
  { id:'pepper',      cat:'spice', en:'Black pepper',   mr:'काळी मिरी',         hi:'काली मिर्च',        tr:'kali miri', staple:true },
  { id:'bayleaf',     cat:'spice', en:'Bay leaf',       mr:'तमालपत्र',          hi:'तेज पत्ता',         tr:'tamalpatra', staple:true },
  { id:'cinnamon',    cat:'spice', en:'Cinnamon',       mr:'दालचिनी',           hi:'दालचीनी',          tr:'dalchini', staple:true },
  { id:'ginger',      cat:'spice', en:'Ginger',         mr:'आले',              hi:'अदरक',            tr:'aale', staple:true },
  { id:'garlic',      cat:'spice', en:'Garlic',         mr:'लसूण',             hi:'लहसुन',            tr:'lasun', staple:true },
  { id:'lemon',       cat:'spice', en:'Lemon',          mr:'लिंबू',             hi:'नींबू',            tr:'limbu' },
  { id:'jaggery',     cat:'spice', en:'Jaggery',        mr:'गूळ',              hi:'गुड़',             tr:'gul' },
  { id:'eno',         cat:'spice', en:'Eno / baking soda', mr:'इनो',           hi:'ईनो',             tr:'eno' },

  // ---------- OTHER ----------
  { id:'coconut',     cat:'other', en:'Fresh coconut',  mr:'नारळ',             hi:'नारियल',           tr:'naral' },
  { id:'coconutmilk', cat:'other', en:'Coconut milk',   mr:'नारळाचे दूध',       hi:'नारियल का दूध',     tr:'naralache dudh' },
  { id:'cashew',      cat:'other', en:'Cashews',        mr:'काजू',             hi:'काजू',            tr:'kaju' },
  { id:'peanut',      cat:'other', en:'Peanuts',        mr:'शेंगदाणे',          hi:'मूंगफली',          tr:'shengdane' },
  { id:'banana',      cat:'other', en:'Bananas',        mr:'केळी',             hi:'केला',            tr:'keli' },
  { id:'fruit',       cat:'other', en:'Seasonal fruit', mr:'हंगामी फळे',        hi:'मौसमी फल',         tr:'hangami phale' },
];

const CATEGORIES = [
  { id:'veg',    en:'Vegetables',        mr:'भाज्या' },
  { id:'greens', en:'Greens & herbs',    mr:'पालेभाज्या आणि हर्ब्ज' },
  { id:'grain',  en:'Dals, grains & flours', mr:'डाळी, धान्य आणि पीठ' },
  { id:'spice',  en:'Spices & staples',  mr:'मसाले' },
  { id:'other',  en:'Other',             mr:'इतर' },
];

/* role: onepot | dal | rice | sabzi | soup | side | snack
   need: must have all;  opt: nice to have, listed if present
   Every recipe here already obeys: vegetarian, no dairy, no chili, low salt. */
const RECIPES = [
  // ---------- ONE-POT MAINS ----------
  { id:'palak-khichdi', role:'onepot',
    en:'Palak khichdi', mr:'पालक खिचडी', hi:'पालक खिचड़ी', tr:'palak khichdi',
    need:['moongdal','rice','spinach','turmeric','jeera'], opt:['onion','tomato','ginger','garlic','lemon'],
    note:'Moong dal + rice + chopped spinach cooked soft together. Toddler-friendly.' },
  { id:'plain-khichdi', role:'onepot',
    en:'Plain khichdi', mr:'साधी खिचडी', hi:'सादी खिचड़ी', tr:'sadhi khichdi',
    need:['moongdal','rice','turmeric','jeera'], opt:['carrot','peas','ginger'],
    note:'Rice + dal + turmeric, cooked very soft.' },
  { id:'veg-khichdi', role:'onepot',
    en:'Vegetable khichdi', mr:'भाज्यांची खिचडी', hi:'सब्ज़ी वाली खिचड़ी', tr:'bhajyanchi khichdi',
    need:['moongdal','rice','turmeric','carrot'], opt:['peas','beans','potato','pumpkin','jeera'],
    note:'Extra soft, extra mild — good for Basil.' },
  { id:'veg-pulao', role:'onepot',
    en:'Vegetable pulao', mr:'भाजी पुलाव', hi:'सब्ज़ी पुलाव', tr:'bhaji pulav',
    need:['rice','carrot','bayleaf','cinnamon','oil'], opt:['peas','beans','potato','onion','cashew','coriander'],
    note:'Whole-spice tempering only — bay leaf and cinnamon, no chili.' },
  { id:'moringa-biryani', role:'onepot', mixer:true,
    en:'Mild moringa & cashew biryani', mr:'सौम्य मोरिंगा-काजू बिर्याणी', hi:'हल्की मोरिंगा-काजू बिरयानी', tr:'saumya moringa-kaju biryani',
    need:['basmati','moringa','cashew','ginger','garlic','carrot'], opt:['beans','peas','onion','tomato','mint','coriander','bayleaf','cinnamon'],
    note:'Ground ginger-garlic-herb paste stands in for chili paste.' },
  { id:'jeera-rice', role:'rice',
    en:'Jeera rice', mr:'जिरा भात', hi:'जीरा चावल', tr:'jira bhat',
    need:['rice','jeera','oil'], opt:['coriander'],
    note:'Plain rice with cumin tempering. No curd, no ghee.' },

  // ---------- DALS ----------
  { id:'moong-dal', role:'dal',
    en:'Plain moong dal', mr:'साधी मूग डाळ', hi:'सादी मूंग दाल', tr:'sadhi moog dal',
    need:['moongdal','turmeric','jeera','hing','oil'], opt:['curryleaf','tomato','coriander','lemon'],
    note:'Boiled soft, light jeera-hing tempering in oil.' },
  { id:'toor-dal', role:'dal',
    en:'Simple tempered toor dal', mr:'साधी तूर डाळ', hi:'सादी तूर दाल', tr:'sadhi toor dal',
    need:['toordal','turmeric','jeera','hing','oil'], opt:['tomato','onion','curryleaf','coriander','jaggery'],
    note:'No chili — just jeera and hing.' },
  { id:'masoor-dal', role:'dal',
    en:'Masoor dal', mr:'मसूर डाळ', hi:'मसूर दाल', tr:'masoor dal',
    need:['masoordal','turmeric','jeera','oil'], opt:['tomato','onion','garlic','coriander'],
    note:'Cooks fastest of the dals.' },
  { id:'dal-drumstick', role:'dal',
    en:'Drumstick dal', mr:'शेवग्याची डाळ', hi:'सहजन की दाल', tr:'shevgyachi dal',
    need:['toordal','drumstick','turmeric','jeera','oil'], opt:['tomato','curryleaf','hing'],
    note:'Drumstick pieces simmered into the dal.' },
  { id:'smooth-dal', role:'dal', mixer:true,
    en:'Smooth blended dal', mr:'गुळगुळीत डाळ', hi:'स्मूद दाल', tr:'gulgulit dal',
    need:['moongdal','turmeric','jeera'], opt:['garlic','ginger','coriander'],
    note:'Blended creamy without any dairy.' },
  { id:'chana-usal', role:'dal',
    en:'Mild chickpea usal', mr:'सौम्य चणा उसळ', hi:'हल्की चना उसल', tr:'saumya chana usal',
    need:['chickpeas','onion','turmeric','dhaniapdr','oil'], opt:['tomato','ginger','garlic','coriander'],
    note:'Soak overnight, pressure cook. No chili powder.' },

  // ---------- SABZIS ----------
  { id:'mixveg-sabzi', role:'sabzi',
    en:'Mixed vegetable sabzi', mr:'मिक्स भाजी', hi:'मिक्स सब्ज़ी', tr:'mix bhaji',
    need:['cauliflower','carrot','potato','turmeric','oil'], opt:['beans','peas','jeera','mustard','coriander'],
    note:'Chopped and sautéed with turmeric and a light tempering.' },
  { id:'cabbage-sabzi', role:'sabzi',
    en:'Cabbage sabzi', mr:'कोबीची भाजी', hi:'पत्ता गोभी की सब्ज़ी', tr:'kobichi bhaji',
    need:['cabbage','turmeric','oil','ginger','garlic'], opt:['peas','carrot','mustard','coriander','tomato'],
    note:'Ginger and garlic finely chopped, not paste — plenty of both.' },
  { id:'bhindi-sabzi', role:'sabzi',
    en:'Bhindi sabzi', mr:'भेंडीची भाजी', hi:'भिंडी की सब्ज़ी', tr:'bhendichi bhaji',
    need:['bhindi','turmeric','oil'], opt:['onion','dhaniapdr','jeera'],
    note:'Sliced and sautéed dry.' },
  { id:'pumpkin-sabzi', role:'sabzi',
    en:'Pumpkin sabzi', mr:'भोपळ्याची भाजी', hi:'कद्दू की सब्ज़ी', tr:'bhoplyachi bhaji',
    need:['pumpkin','turmeric','oil'], opt:['jeera','mustard','jaggery','hing'],
    note:'Sautéed or steamed then lightly mashed.' },
  { id:'potato-sabzi', role:'sabzi',
    en:'Potato sabzi', mr:'बटाट्याची भाजी', hi:'आलू की सब्ज़ी', tr:'batatyachi bhaji',
    need:['potato','turmeric','jeera','oil'], opt:['mustard','curryleaf','coriander','hing'],
    note:'Boiled, then lightly sautéed.' },
  { id:'sweetpotato-sabzi', role:'sabzi',
    en:'Sweet potato sabzi', mr:'रताळ्याची भाजी', hi:'शकरकंद की सब्ज़ी', tr:'ratalyachi bhaji',
    need:['sweetpotato','turmeric','jeera','oil'], opt:['mustard','curryleaf'],
    note:'Boiled and lightly tempered.' },
  { id:'beans-carrot', role:'sabzi',
    en:'Beans and carrot sabzi', mr:'बीन्स-गाजराची भाजी', hi:'बीन्स-गाजर की सब्ज़ी', tr:'beans-gajarachi bhaji',
    need:['beans','carrot','turmeric','oil'], opt:['mustard','coconut','peanut','curryleaf'],
    note:'Fine chopped, quick sauté.' },
  { id:'dudhi-sabzi', role:'sabzi',
    en:'Bottle gourd sabzi', mr:'दुधी भोपळ्याची भाजी', hi:'लौकी की सब्ज़ी', tr:'dudhi bhoplyachi bhaji',
    need:['dudhi','turmeric','jeera','oil'], opt:['tomato','ginger','coriander'],
    note:'Very gentle on the stomach.' },
  { id:'methi-sabzi', role:'sabzi',
    en:'Methi sabzi', mr:'मेथीची भाजी', hi:'मेथी की सब्ज़ी', tr:'methichi bhaji',
    need:['methi','turmeric','oil','garlic'], opt:['potato','onion','peanut'],
    note:'Slightly bitter — pair with a sweet dal.' },
  { id:'shepu-sabzi', role:'sabzi',
    en:'Shepu (dill) sabzi', mr:'शेपूची भाजी', hi:'सोआ की सब्ज़ी', tr:'shepuchi bhaji',
    need:['shepu','turmeric','oil'], opt:['moongdal','garlic','peanut'],
    note:'Often made with a handful of moong dal.' },
  { id:'beet-sabzi', role:'sabzi',
    en:'Beetroot sabzi', mr:'बीटाची भाजी', hi:'चुकंदर की सब्ज़ी', tr:'beetachi bhaji',
    need:['beetroot','turmeric','oil'], opt:['coconut','mustard','curryleaf','lemon'],
    note:'Grated and quickly cooked. Basil will like the colour.' },
  { id:'capsicum-besan', role:'sabzi',
    en:'Capsicum-besan sabzi', mr:'ढोबळी मिरची-बेसन भाजी', hi:'शिमला मिर्च-बेसन सब्ज़ी', tr:'dhobli mirchi-besan bhaji',
    need:['capsicum','besan','turmeric','oil'], opt:['jeera','hing','coriander'],
    note:'Sweet capsicum only, no chili.' },
  { id:'mild-gravy', role:'sabzi', mixer:true,
    en:'Mild vegetable gravy', mr:'सौम्य भाजीची ग्रेव्ही', hi:'हल्की सब्ज़ी की ग्रेवी', tr:'saumya bhajichi gravy',
    need:['onion','tomato','turmeric','oil','cauliflower'], opt:['coconutmilk','cashew','ginger','garlic','peas','carrot','coriander'],
    note:'Onion-tomato base ground smooth. No cream — a splash of coconut milk if richness is wanted.' },

  // ---------- STEAMED / SIDES ----------
  { id:'steamed-veg', role:'side',
    en:'Steamed vegetables', mr:'वाफवलेल्या भाज्या', hi:'भाप में पकी सब्ज़ियाँ', tr:'vaphavlelya bhajya',
    need:['broccoli'], opt:['cauliflower','carrot','beans','salt','oil','lemon'],
    note:'Plain, or a drizzle of oil and a pinch of salt. No butter.' },
  { id:'boiled-sweetpotato', role:'side',
    en:'Boiled sweet potato', mr:'उकडलेली रताळी', hi:'उबले शकरकंद', tr:'ukadleli ratali',
    need:['sweetpotato'], opt:['salt','lemon'],
    note:'Doubles as a toddler snack.' },
  { id:'cucumber-koshimbir', role:'side',
    en:'Cucumber koshimbir (no curd)', mr:'काकडीची कोशिंबीर', hi:'खीरे की कोशिंबीर', tr:'kakdichi koshimbir',
    need:['cucumber'], opt:['peanut','coriander','lemon','jaggery','salt'],
    note:'Dry version — peanut powder instead of curd.' },
  { id:'fruit-plate', role:'side',
    en:'Fresh fruit plate', mr:'ताज्या फळांची प्लेट', hi:'ताज़े फलों की प्लेट', tr:'tajya phalanchi plate',
    need:['fruit'], opt:['banana','lemon'],
    note:'Washed in drinking water.' },

  // ---------- SOUPS ----------
  { id:'palak-dal-soup', role:'soup',
    en:'Palak-dal soup', mr:'पालक-डाळीचे सूप', hi:'पालक-दाल का सूप', tr:'palak-dalyache soup',
    need:['spinach','moongdal','garlic','ginger','turmeric'], opt:['lemon','pepper','coriander'],
    note:'Boiled soft and mashed by hand with a ladle. Good for a sore throat.' },
  { id:'tomato-veg-soup', role:'soup',
    en:'Tomato-vegetable soup', mr:'टोमॅटो-भाज्यांचे सूप', hi:'टमाटर-सब्ज़ी का सूप', tr:'tomato-bhajyanche soup',
    need:['tomato','carrot'], opt:['garlic','ginger','pepper','coriander','beetroot'],
    note:'Boiled soft, hand-mashed. Skip the cream and butter finish.' },
  { id:'mixveg-soup', role:'soup',
    en:'Mixed vegetable soup', mr:'मिश्र भाज्यांचे सूप', hi:'मिक्स सब्ज़ी का सूप', tr:'mishra bhajyanche soup',
    need:['carrot','cauliflower'], opt:['beans','peas','potato','garlic','pepper','moringa'],
    note:'Whatever is in the fridge, boiled soft.' },
  { id:'pureed-soup', role:'soup', mixer:true,
    en:'Pureed vegetable soup', mr:'भाज्यांचे स्मूद सूप', hi:'सब्ज़ियों का स्मूद सूप', tr:'bhajyanche smooth soup',
    need:['pumpkin'], opt:['carrot','tomato','garlic','ginger','coconutmilk','pepper'],
    note:'Blended smooth — easiest for the toddler.' },
  { id:'jeera-tea', role:'side',
    en:'Jeera tea', mr:'जिऱ्याचा चहा', hi:'जीरे की चाय', tr:'jiryacha chaha',
    need:['jeera'], opt:['ginger','lemon','jaggery'],
    note:'Cumin boiled in water. Good after meals.' },

  // ---------- SNACKS / BREAKFAST ----------
  { id:'poha', role:'snack',
    en:'Poha', mr:'पोहे', hi:'पोहा', tr:'pohe',
    need:['poha','turmeric','mustard','oil'], opt:['potato','peas','onion','peanut','curryleaf','coriander','lemon'],
    note:'No chili. Lemon at the end.' },
  { id:'upma', role:'snack',
    en:'Upma', mr:'उपमा', hi:'उपमा', tr:'upma',
    need:['rava','oil','mustard'], opt:['carrot','peas','onion','curryleaf','ginger','coriander'],
    note:'Mild tempering, plenty of vegetables.' },
  { id:'idli', role:'snack',
    en:'Steamed idli', mr:'वाफवलेली इडली', hi:'इडली', tr:'vaphavleli idli',
    need:['idlibatter'], opt:['coriander','coconut'],
    note:'Store-bought batter, steamed.' },
  { id:'besan-bread', role:'snack',
    en:'Besan steamed bread', mr:'बेसनाचा वाफवलेला ब्रेड', hi:'बेसन की स्टीम ब्रेड', tr:'besanacha vaphavlela bread',
    need:['besan','eno'], opt:['turmeric','ginger','coriander','oil'],
    note:'The besan + Eno bread already tried.' },
  { id:'dhokla', role:'snack', mixer:true,
    en:'Dhokla', mr:'ढोकळा', hi:'ढोकला', tr:'dhokla',
    need:['besan','eno','ginger'], opt:['mustard','curryleaf','coriander','lemon','jaggery'],
    note:'Steamed and soft, no chili in the tempering.' },
  { id:'thalipeeth', role:'snack', mixer:true,
    en:'Thalipeeth', mr:'थालीपीठ', hi:'थालीपीठ', tr:'thalipeeth',
    need:['jowar','besan','atta','onion'], opt:['coriander','turmeric','oil','methi'],
    note:'Mixed-flour flatbread, mild version without chili.' },
  { id:'chapati', role:'side',
    en:'Chapati / poli', mr:'पोळी', hi:'रोटी', tr:'poli',
    need:['atta','oil'], opt:['salt'],
    note:'Needs the rolling pin.' },
  { id:'stuffed-paratha', role:'snack', mixer:true,
    en:'Stuffed paratha', mr:'भरलेला पराठा', hi:'भरवां पराठा', tr:'bharlela paratha',
    need:['atta','oil','carrot'], opt:['cauliflower','potato','coriander','ginger','turmeric'],
    note:'Filling ground or mashed fine.' },
  { id:'dosa-batter', role:'snack', mixer:true,
    en:'Homemade dosa / idli batter', mr:'घरचे डोसा-इडली पीठ', hi:'घर का डोसा-इडली बैटर', tr:'gharche dosa-idli pith',
    need:['rice','uraddal'], opt:['methi'],
    note:'Ground and fermented overnight.' },

  // ---------- CHUTNEYS ----------
  { id:'coconut-chutney', role:'side', mixer:true,
    en:'Coconut chutney', mr:'नारळाची चटणी', hi:'नारियल की चटनी', tr:'naralachi chatni',
    need:['coconut','ginger'], opt:['roastedgram','curryleaf','mustard','oil','lemon'],
    note:'Mild — just skip the green chili.' },
  { id:'coriander-chutney', role:'side', mixer:true,
    en:'Coriander-mint chutney', mr:'कोथिंबीर-पुदिना चटणी', hi:'धनिया-पुदीना चटनी', tr:'kothimbir-pudina chatni',
    need:['coriander','mint'], opt:['lemon','ginger','garlic','peanut','jaggery'],
    note:'No green chili.' },
  { id:'tomato-chutney', role:'side', mixer:true,
    en:'Tomato chutney', mr:'टोमॅटोची चटणी', hi:'टमाटर की चटनी', tr:'tomatochi chatni',
    need:['tomato','oil'], opt:['garlic','jaggery','mustard','curryleaf','hing'],
    note:'Mild, no chili.' },
];
